### PR TITLE
✨ Fix missing URL for Top-level menu entry in nested menu

### PR DESCRIPTION
**Pull request by schachem**
I hope this is okay.
I am explicitly checking if there even is a url, and if so, include it.

### CODE REVIEW

**Comment by schachem** [comment]
Fixes #688

**Comment by schachem** [comment]
Well, that was some sort of quick shot from my side; just noticed that I violated a few contributing guidelines as I did not really take the time to properly read through them as it was such a minor change.
If you agree to include this change though, I can open another PR and properly adhere to the guidelines :)

**Comment by nunocoracao** [comment]
Thanks for the contribution @schachem. And don't worry about the guidelines, no harm done. A couple of asks though which I hope you don't mind making as part of the same PR

1) update docs 
 i.e. - https://blowfish.page/docs/getting-started/#nested-menus
this part `Note that pageRef and url will be ignored for the parent entry.`

2) Even though I think the behavior will be weird I don't mind supporting this, however, let's do it in one go. i.e. You should also check for `pageRef` and make sure to support both, meaning one OR the other OR none as of today.  

Let me know if it makes sense and if you don't mind updating the PR. 

Thanks again for the help

**Comment by nunocoracao** [comment]
@schachem just checking for an ack, do you agree with the comments?

**Comment by schachem** [comment]
Yes, more or less.

However, I am not sure about the remark regarding `pageRef`.

In my experience, either page ref or a url being set in the menu properties will lead to an .URL param being present or not.

So I think one does not need to check the if pageRef is set.

But I will look into it more thorough

**Comment by nunocoracao** [comment]
@schachem fair point. You might be right don't remember that part of the codebase would need to check. Documentation-wise at least both should be mentioned as supported.

**Comment by nunocoracao** [comment]
@schachem will update the docs myself
Thanks again

**Comment by nunocoracao** [comment]
fixes https://github.com/nunocoracao/blowfish/issues/688

**Pull request merged**
