### PR TITLE
Add my personal site to users.json

### PR DESCRIPTION
**Pull request by JahsehJ**
<3 your great works!

### CODE REVIEW

**Comment by JahsehJ** [comment]
It seems like my original commit was overwritten by other's 😂

**Comment by JahsehJ** [comment]
@nunocoracao do I reopen PR or you will just fix it? Many thanks 👍

**Comment by nunocoracao** [comment]
Man... my bad... sorry there was conflicts and I f'd up. Send me the details here and I'll add it myself if you prefer. Otherwise yes you can open a new PR.

**Comment by JahsehJ** [comment]
It's all good mate! I'll open a new PR later to save you some time.

**Comment by nunocoracao** [comment]
No need mate I got you - doing a patch release for this plus a couple of updates

**Comment by JahsehJ** [comment]
Oh alright. It's https://jahsehj.github.io !

**Pull request merged**
