### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by pfrogond**
Hello, I would like to submit czech translation.

### CODE REVIEW

**Comment by nunocoracao** [comment]
Thanks @pfrogond

**Comment by nunocoracao** [comment]
@pfrogond may I ask you to add the line with the language to https://nunocoracao.github.io/blowfish/docs/configuration/#language-and-i18n do that this gets to the docs? 

Thanks

**Comment by pfrogond** [comment]
@nunocoracao done

**Comment by nunocoracao** [comment]
Thanks @pfrogond

**Pull request merged**
