### PR TITLE
🔖 v2.63.0

### PR DESCRIPTION
**Pull request by nunocoracao**

### CODE REVIEW

**Comment by nunocoracao** [comment]
FYI @Aphcity build is breaking

>ERROR render of "section" failed: "/blowfish/layouts/_default/list.html:23:21": execute of template failed: template: _default/list.html:23:21: executing "main" at <.File.Path>: can't evaluate field File in type *source.File
Built in 363 ms

**Comment by nunocoracao** [comment]
@Aphcity build i failing - I think it's because of your last PR 
will have a look
>ERROR render of "section" failed: "/home/runner/work/blowfish/blowfish/layouts/_default/list.html:24:12": execute of template failed: template: _default/list.html:24:12: executing "main" at <.AllTranslations>: can't evaluate field AllTranslations in type source.File
Total in 10408 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/home/runner/work/blowfish/blowfish/layouts/_default/list.html:24:12": execute of template failed: template: _default/list.html:24:12: executing "main" at <.AllTranslations>: can't evaluate field AllTranslations in type source.File
Error: Process completed with exit code 1.

**Comment by nunocoracao** [comment]
@Aphcity fixed 👍🏼

**Comment by nunocoracao** [comment]
@Aphcity are you using any tools to speed up translation?

**Comment by Aphcity** [comment]
> @Aphcity are you using any tools to speed up translation?

Yeah, for sure, it's [Comment Translate](https://github.com/intellism/vscode-comment-translate) with DeepL API in VSCode. And then modify to normal language we speak in reallife. But there are still some conflicts with Weaxs' translation, I will unify all the terms and documents in Chinese later.

**Pull request merged**
