### PR TITLE
✨ Mobile classes for gallery and carousel

### LINKED ISSUE #482: ✨ Mobile specific classes for gallery width
**Is your feature request related to a problem? Please describe.**

Currently, I can only set the width for a gallery element globally, so it is the same regardless of the screen width. For example, a `grid-w20` might look OK on a desktop device, but it will be very tiny on mobile.

**Describe the solution you'd like**

I would like mobile specific classes for grid widths, so that I could set something like `class="grid-w20 md:grid-w45"` to have specific layouts for mobile and desktop.

### PR DESCRIPTION
**Pull request by mirceanton**
Fixes #482

### CODE REVIEW

**Comment by nunocoracao** [comment]
Hello @mirceanton do we really need this? 
I think without this CSS you were already able to use md:CLASS

**Comment by mirceanton** [comment]
I think the css classes were not present before. I tried to set the class but nothing was happening. Maybe i was doing something wrong?

**Comment by nunocoracao** [comment]
@mirceanton not forgotten just won't have time to review this now

**Comment by nunocoracao** [comment]
I merged the changes, the code doesn't work

**Comment by nunocoracao** [comment]
@mirceanton had to redo the ode... check this commit if interested
https://github.com/nunocoracao/blowfish/commit/5ab7918e1f732b66b9816b5deb65a2d34968b671

**Comment by mirceanton** [comment]
@nunocoracao ah... I see where I went wrong... Sorry about that! 😅

**Comment by nunocoracao** [comment]
no problem. next time test it please

**Comment by mirceanton** [comment]
I did test similar changes directly on my website by doing the modifications locally, but I think I only tested on mobile. Perhaps the "mobile-specific" classes were overriding the "regular" ones and that's why I assumed it was working fine.

Yeah... note taken! I'll be more thorough with my testing!

**Pull request merged**
