### PR TITLE
Change title to fix folder name for Windows user

### PR DESCRIPTION
**Pull request by michaeldorner**
This PR fixes the issue for Windows users introduced in #1780 by a title that contains `:` (thanks @eallion for the hint!)

### CODE REVIEW

**Comment by eallion** [comment]
😊

**Comment by unacro** [comment]
And it's the right way for fix #1835.

Good job. Hope to merge it ASAP.

**Comment by deining** [comment]
> And it's the right way for fix #1835.

I agree.

However, this PR does not fully resolve #1835. Even with this PR in place, you get an error when using this theme as go/hugo module:

```
go get github.com/michaeldorner/blowfish/v2@8f6778d80d0055e9d2070d1e7085d035dd8c453d
go: downloading github.com/michaeldorner/blowfish/v2 v2.0.0-20241109090851-8f6778d80d00
go: github.com/michaeldorner/blowfish/v2@8f6778d80d0055e9d2070d1e7085d035dd8c453d: create zip: exampleSite/content/users/Xeonzilla’s Note/feature.jpg: malformed file path "exampleSite/content/users/Xeonzilla’s Note/feature.jpg": invalid char '’'
exampleSite/content/users/Xeonzilla’s Note/index.it.md: malformed file path "exampleSite/content/users/Xeonzilla’s Note/index.it.md": invalid char '’'
exampleSite/content/users/Xeonzilla’s Note/index.ja.md: malformed file path "exampleSite/content/users/Xeonzilla’s Note/index.ja.md": invalid char '’'
exampleSite/content/users/Xeonzilla’s Note/index.md: malformed file path "exampleSite/content/users/Xeonzilla’s Note/index.md": invalid char '’'
exampleSite/content/users/Xeonzilla’s Note/index.zh-cn.md: malformed file path "exampleSite/content/users/Xeonzilla’s Note/index.zh-cn.md": invalid char '’'
```

This is due to the use of `’` in a directory name.

**Comment by michaeldorner** [comment]
Sorry for the slopy work. I fixed it. 

Since we partially use already domains as folder names, may I suggest to consistently roll out this naming convention?

**Comment by unacro** [comment]
> Darn, sorry for the sloppy work. I fixed it.
> 
> Since we partially use already domains as folder names, may I suggest to consistently roll out this naming convention to avoid this problem in the future?

Can't agree more. Similar situations is as hell

**Comment by nunocoracao** [comment]
Fixing this in v2.80.0

**Pull request closed without merging**
