### PR TITLE
✨ Add player parameters for youtubeLite shortcode

### PR DESCRIPTION
**Pull request by d4rklynk**
https://github.com/paulirish/lite-youtube-embed?tab=readme-ov-file#custom-player-parameters

### CODE REVIEW

**Comment by nunocoracao** [comment]
Hello @d4rklynk PR looks good, it's missing the documentaiton update. Can you please add to this PR?

**Comment by d4rklynk** [comment]
Done, let me know what you think

**Comment by nunocoracao** [comment]
@d4rklynk looks better - could you add the detailed list of parameters in the docs or surface them as individual parameters at the top level?

**Comment by d4rklynk** [comment]
Do you mean explaining all the parameters described in the Google docs or just list them?

**Comment by nunocoracao** [comment]
At least point people to where to find the parameters (sorry if it's already there and I missed it) if we keep the params var.

**Comment by d4rklynk** [comment]
Indeed, I set it to the last paragraph.

I can rephrase though if you want.

**Comment by nunocoracao** [comment]
Nothing need thanks. Sorry for missing it.

**Pull request merged**
