### PR TITLE
✨ Zen-mode feature

### PR DESCRIPTION
**Pull request by v20100v**
See issue https://github.com/nunocoracao/blowfish/discussions/1084

### CODE REVIEW

**Comment by v20100v** [comment]
A video to show the behavior of this feature

https://github.com/nunocoracao/blowfish/assets/7567933/2cef16e7-413c-4b55-a4f9-bc1a62300213

**Comment by nunocoracao** [comment]
@v20100v 🤩
Boy this is a big one, will need time to review. Would you be able to add the documentation changes required for this one? I assume for a user would just be the parameter in the config on or off.

**Comment by v20100v** [comment]
Hello @nunocoracao (and happy new year ^^.)

If I find time, I will write the documentation for this feature. Returning to work leaves me little freedom.

**Comment by nunocoracao** [comment]
@v20100v don't sweat it I did it :) 
Might submit some improvements in the future and tag you for review.

**Comment by v20100v** [comment]
Sound good. 
Maybe I could write an article to showcase the zen-mode feature in https://blowfish.page/samples/ if you want ?

> *Might submit some improvements in the future and tag you for review.*
Of course with pleasure ^^.

**Pull request merged**
