### PR TITLE
🎏 Added: Japanese translation (`authors/**` and `samples/**`)

### PR DESCRIPTION
**Pull request by Lemon73-Computing**
#1358

- [x] authors
  - [x] Nuno Coração
  - [x] secondauthor
- [x] samples
  - [x] (index.md)
  - [x] charts
  - [x] diagrams-flowcharts
  - [x] emoji
  - [x] external
  - [x] icons
  - [x] markdown
  - [x] mathematical-notation
  - [x] multiplie-authors
  - [x] placeholder-text
  - [x] rich-content
  - [x] thumbnail_sample

### CODE REVIEW

**Comment by nunocoracao** [comment]
@Lemon73-Computing are you still planning on wrapping this one?

**Comment by Lemon73-Computing** [comment]
@nunocoracao Yes. However It will take time to finish.

**Comment by nunocoracao** [comment]
@Lemon73-Computing are you ok with fixing all the conflicts?

**Comment by Lemon73-Computing** [comment]
@nunocoracao Thank you for waiting.

**Comment by nunocoracao** [comment]
Will do @Lemon73-Computing thanks for the help
Updated https://github.com/nunocoracao/blowfish/issues/1358 to reflect this change

**Pull request merged**
