### PR TITLE
✨ Custom colors for alert shortcode

### LINKED ISSUE #483: ✨ Customizable alert card
**Is your feature request related to a problem? Please describe.**

Currently we can only customize the icon for the alert shortcode, not the colors.

**Describe the solution you'd like**

I would like the colors for both the card and the icon itself to be customizable. For example, having a red card with a black warning icon for very important things etc.

### PR DESCRIPTION
**Pull request by mirceanton**
Fixes #483

### CODE REVIEW

**Comment by mirceanton** [comment]
Not sure if the way I tried to implement "optional" parameters is the actual proper way. Looking for some fedback.

**Comment by nunocoracao** [comment]
Can we add a table with all the params to the docs for this?

**Comment by mirceanton** [comment]
Sure! I'll add it tomorrow

**Comment by mirceanton** [comment]
I lied. I did it today!

image

**Comment by nunocoracao** [comment]
I think we can collapse those notes into the table itself thoughts?

**Comment by mirceanton** [comment]
image

Something like this perhaps?

**Comment by nunocoracao** [comment]
@mirceanton u rock

**Comment by nunocoracao** [comment]
Just noticed something, this is a breaking change isn't it?
People using the current Alert shortcode will have problems with this change aka it will stop working.

**Comment by nunocoracao** [comment]
Idea: instead of replacing the old shortcode, why don't we create a new one? I know it sucks in terms of code... but whoever is using an older version won't have their site broken when they update. thoughts?

**Comment by nunocoracao** [comment]
Alternatively, if there is a way to keep the same syntax for icons as before that would be great. I don't think there is but you seem to be more comfortable with the argument passing in partials than I am. 

@mirceanton check above messages when you have time

**Comment by mirceanton** [comment]
@nunocoracao I am almost sure there is a way to make this work. I remember reading something in the hugo docs at some point.

https://gohugo.io/templates/shortcode-templates/#isnamedparams

I think this should do. I'll give it a try

**Comment by mirceanton** [comment]
@nunocoracao I think this should do! It now works both ways.

Not really sure how to cleanup/organize the code. I think those if statements look a bit ugly, but I didn't find a tidier alternative.

**Pull request merged**
