### PR TITLE
Improve visuals of sharing links

### PR DESCRIPTION
**Pull request by chrisbanes**
The current sharing icons are currently anchored to the bottom with uneven visual padding around this. The PR changes them to be centred.

Current:
Screenshot 2022-11-16 at 13 47 51

With PR:
Screenshot 2022-11-17 at 10 15 30

### CODE REVIEW

**Comment by nunocoracao** [comment]
Hello @chrisbanes the `p-2` exists check https://tailwindcss.com/docs/padding
In order to get it working you might need to run `npm run build` or `npm run dev` to have live reload of the final CSS file. Do you want to try these options?

**Comment by chrisbanes** [comment]
Updated!

**Comment by nunocoracao** [comment]
Merging into dev branch want to solve some other tickets before making a new release (next week hopefully)

**Comment by nunocoracao** [comment]
Might need to revert this @chrisbanes creates other places to malfunction... will try to implement the change in the sharing component

**Comment by chrisbanes** [comment]
What's malfunctioning? It should be localised to the icons divs I think?

**Comment by nunocoracao** [comment]
Already fixed... had to remove the padding from icons into sharing component. Also had to review all places in theme where icons were used they broke e.g. views/likes icons.

I think everything is working now and the result for the sharing icons is the same you wanted. Please do check and let me know.

**Pull request merged**
