### PR TITLE
🎏 Blowfish translation 

### PR DESCRIPTION
**Pull request by nunocoracao**
Created the skeleton for the menu and language files for IT JA and ZH-CN
Goal will be to translate those and every index.md and _index.md file in the content folder. I would like to keep the same folder structure so plese duplicate the files themselves e.g. for a given index.md create a index.ja.md for the japanese translation. Note: don't forget to translate lists first (_index.md) otherwise Hugo breaks with non-obvious error messages.

- [ ] Generate menu and language configs files for each target language
- [ ] Translate every index.md and _index.md file in content folder, e.g. for it create a index.it.md or a _index.it.md

### CODE REVIEW

**Comment by nunocoracao** [comment]
Thanks @Weaxs for the first drop. Are you planning to translate more pages?

**Comment by Weaxs** [comment]
> . Are you planning to translate more pages?

Yes, I will translate more pages in spare time.

**Comment by nunocoracao** [comment]
@Weaxs FYI - ERROR [zh-cn] REF_NOT_FOUND: Ref "advanced": "/home/runner/work/blowfish/blowfish/exampleSite/content/tags/_index.zh-cn.md:6:91": page not found

**Comment by Weaxs** [comment]
> @Weaxs FYI - ERROR [zh-cn] REF_NOT_FOUND: Ref "advanced": "/home/runner/work/blowfish/blowfish/exampleSite/content/tags/_index.zh-cn.md:6:91": page not found

I commit a pr for {{< ref "advanced" >}} https://github.com/nunocoracao/blowfish/pull/1330

**Comment by nunocoracao** [comment]
> > @Weaxs FYI - ERROR [zh-cn] REF_NOT_FOUND: Ref "advanced": "/home/runner/work/blowfish/blowfish/exampleSite/content/tags/_index.zh-cn.md:6:91": page not found
> 
> I commit a pr for {{< ref "advanced" >}} #1330

FYI did a commit to fix the sub-menus structure in Examples

**Comment by Weaxs** [comment]
@nunocoracao I want to use single `index.md `for multiple languages, such like `index.md` in folder `exampleSite/content/users`.  

I found this question in hugo discourse: [Single markdown for multiple languages](https://discourse.gohugo.io/t/single-markdown-for-multiple-languages/25552) and [I18n: A way to force page generation even if it isn’t translated?](https://discourse.gohugo.io/t/i18n-a-way-to-force-page-generation-even-if-it-isnt-translated/24438), and I also found a option [enableMissingTranslationPlaceholders](https://gohugo.io/getting-started/configuration/)、[Missing translations](https://gohugo.io/content-management/multilingual/#missing-translations). 

But it is not work locally when I try to set `enableMissingTranslationPlaceholders` in `exampleSite/config/_default/hugo.toml` . 
 And this option is global, some riks maybe occur ? The optioon just for article or listing page not global maybe better.

Do you have any other solutions ? thx for your reply.

**Comment by nunocoracao** [comment]
I also checked that but was under the impression is not possible. I can explore that one. Let's do the following, don't worry about the users page for now. Worse case scenario I'll add it to the script.

**Comment by nunocoracao** [comment]
> @nunocoracao I want to use single `index.md `for multiple languages, such like `index.md` in folder `exampleSite/content/users`.
> 
> I found this question in hugo discourse: [Single markdown for multiple languages](https://discourse.gohugo.io/t/single-markdown-for-multiple-languages/25552) and [I18n: A way to force page generation even if it isn’t translated?](https://discourse.gohugo.io/t/i18n-a-way-to-force-page-generation-even-if-it-isnt-translated/24438), and I also found a option [enableMissingTranslationPlaceholders](https://gohugo.io/getting-started/configuration/)、[Missing translations](https://gohugo.io/content-management/multilingual/#missing-translations).
> 
> But it is not work locally when I try to set `enableMissingTranslationPlaceholders` in `exampleSite/config/_default/hugo.toml` . And this option is global, some risks maybe occur ? The optioon just for article or listing page not global maybe better.
> 
> Do you have any other solutions ? thx for your reply.

@Weaxs I tried to use some of this solutions - including symlinks to populate a new language (see genLanLinks.js) and nothing worked. The configs in those files don't seem to do anything, and Hugo doesn't read symlinks apparently... On a good side, updated the user generation script to generate all required language index files and also translate tags in real time. Wrapping up some optimizations before committing. 

Also added a new config for disabling languages. This will enable us to merge this branch into dev/main if this is taking too long and continuing with the translation work in dev while having them hidden in production.

**Comment by nunocoracao** [comment]
@Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity  I've just committed a an update with all the placeholder files for all languages. I think this is going to take a while to translate. Shall we disable all languages that are not fully translated until they are, or leave the placeholders and people will translate the missing pages over time?

**Comment by Aphcity** [comment]
> @Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity I've just committed a an update with all the placeholder files for all languages. I think this is going to take a while to translate. Shall we disable all languages that are not fully translated until they are, or leave the placeholders and people will translate the missing pages over time?

I think we cound leave them, people who want to use another language for their website must have the ability to translate them. Leave them and we might get more people contributing to this branch.

**Comment by nunocoracao** [comment]
> > @Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity I've just committed a an update with all the placeholder files for all languages. I think this is going to take a while to translate. Shall we disable all languages that are not fully translated until they are, or leave the placeholders and people will translate the missing pages over time?
> 
> I think we cound leave them, people who want to use another language for their website must have the ability to translate them. Leave them and we might get more people contributing to this branch.

Ok so in my opinion, I think this branch is looking good. Thanks to everyone for their contributions. This should be good enough to go live and we can continue translating to other languages as people can/want to contribute. I propose merging this one to dev (next release) and publishing everything. Going forward translations become normal PRs on dev branch. thoughts?

We can still track all the missing translation pages here and optionally HIDE some languages in the production deployment.

**Comment by nunocoracao** [comment]
Ok going to merge to dev let's continue work there

**Pull request merged**
