### PR TITLE
Added fediverse Author attribution attribute

### PR DESCRIPTION
**Pull request by MayMeow**
Yesterday Mastodon [4.3.0 was released](https://blog.joinmastodon.org/2024/10/mastodon-4.3/) And, among other features, added the ability to attribute yourself to links from your site. 

It adds a small tag (by / more from) - profile link - under all links from allowed domains that the other or you share on Mastodon. For better illustration it looks like:

image

It can be done by adding new meta tag `ediverse:creator` to head of your website. 

I updated the Head Partial and added new parameters under Verification. (As in Mastodon, this option is under Profile -> Verification -> Author attribution)

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
@MayMeow can you also add documentation as to how this works? (i.e. what values to edit, how to format the fediverse handle)

**Review by Ast3risk-ops — CHANGES_REQUESTED** [review]
In the docs, instead of Mastodon handle put Fediverse handle and the supported fedi software (if applicable).

**Comment by MayMeow** [comment]
> In the docs, instead of Mastodon handle put Fediverse handle and the supported fedi software (if applicable).

Like this one:  "The fediverse handle to include in the site metadata. Include the server domain in the username, e.g. `@you@instanceaddress.tld` This is currently supported on Mastodon." ?


 To display this verification, you need to configure your account. From my latest knowledge, this is possible on Mastodon.

**Comment by MayMeow** [comment]
To add to it, this verification is then displayed on the web and the official Mastodon application under shared links to your site.

Other apps like Ivory (iOS), Ice Cubes (iOS), or Mona (iOS) also support this.

**Comment by Ast3risk-ops** [comment]
> > In the docs, instead of Mastodon handle put Fediverse handle and the supported fedi software (if applicable).
> 
> Like this one: "The fediverse handle to include in the site metadata. Include the server domain in the username, e.g. `@you@instanceaddress.tld` This is currently supported on Mastodon." ?
> 
> _To display this verification, you need to configure your account. From my latest knowledge, this is possible on Mastodon._

just replace Mastodon with fediverse, you can link to a profile on any fediverse software even if the link will only show up if your page is shared on Mastodon.

**Review by Ast3risk-ops — APPROVED** [review]
Yeah, like that.

**Comment by nunocoracao** [comment]
Thanks @MayMeow and @Ast3risk-ops

**Pull request merged**
